language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - openjdk8  
  - openjdk11
services:
  - redis-server
after_success:
  - mvn clean test jacoco:report coveralls:report

cache:
  directories:
  - $HOME/.m2
